//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureContactManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShippingMethodRestriction
    {
        public int ShippingMethod_Id { get; set; }
        public int Country_Id { get; set; }
    }
}
